server:
  port: 20000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.com.atguigu.gulimall.search: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
