server:
  port: 88

spring:
  application:
    name: gulimall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false    #开启注册中心路由功能
      routes:
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>/?.*),/product/$\{segment}

        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/sys/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

